//State products
export const PLATES_TYPES = {
  GET_PLATES: 'GET_PLATES',
  SELECT_PLATE: 'SELECT_PLATE',
  ADD_PLATE_TO_ORDERS: 'ADD_PLATE_TO_ORDERS',
  SHOW_ORDER_RESUME: 'SHOW_ORDER_RESUME',
  REMOVE_PLATE_FROM_ORDER: 'REMOVE_PLATE_FROM_ORDER',
  SAVE_ORDER_ID: 'SAVE_ORDER_ID',
};
